local M = {}
M.symbols = {
	Fragment = "",
	Component = "",
	Implementation = "",
	Namespace = "󰌗",
	Package = "",
	TypeParameter = "󰅲",
	Undefined = "",
	TypeAlias = "",
	Parameter = "",
	StaticMethod = "",
	Macro = "",
	Array = "󰅪",
	Boolean = "",
	Null = "󰟢",
	Number = "",
	Object = "󰅩",
	String = "󰉿",
	Default = "",
	Files = "",
	FileTree = "󰙅",
	Import = "",
	Symlink = "",
	Text = "󰉿",
	Method = "󰆧",
	Function = "󰊕",
	Constructor = "",
	Field = "󰜢",
	Variable = "󰀫",
	Class = "󰠱",
	Interface = "",
	Module = "",
	Property = "󰜢",
	Unit = "󰑭",
	Value = "󰎠",
	Enum = "",
	Keyword = "󰌋",
	Snippet = "",
	Color = "󰏘",
	File = "󰈙",
	Reference = "󰈇",
	Folder = "󰉋",
	EnumMember = "",
	Constant = "󰏿",
	Struct = "󰙅",
	Event = "",
	Operator = "󰆕",
}

M.cmp = {
	Codeium = "",
	TabNine = "",
	Copilot = "",
	buffer = "",
	cmp_tabnine = "",
	codeium = "",
	copilot = "",
	copilot_alt = "",
	latex_symbols = "",
	luasnip = "󰃐",
	nvim_lsp = "",
	nvim_lua = "",
	orgmode = "",
	path = "",
	spell = "󰓆",
	tmux = "",
	treesitter = "",
	undefined = "",
}

M.diagnostics = {
	Hint = "",
	Info = "",
	Warning = "",
	Error = "",
}

M.git = {
	Modified = "●",
	Unstaged = "",
	Staged = "",
	Conflict = "שׂ",
	Renamed = "",
	Untracked = "ﲉ",
	Deleted = "",
	Ignored = "",
}

M.dap = {
	BreakPoint = "",
	BreakPointCondition = "ﳁ",
	BreakPointRejected = "",
	LogPoint = "",
	Stopped = "",
	Terminate = "󰝤",
	Pause = "",
	Play = "",
	RunLast = "↻",
	StepBack = "",
	StepInto = "󰆹",
	StepOut = "󰆸",
	StepOver = "󰆷",
}

M.ui = {
	ArrowClose = "",
	ArrowOpen = "",
	Indicator = "",
}

return M
